// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDle2wA0Z__I_SShGNLg8fxuiIuh8_I7GM',
    appId: '1:360056616553:web:70733c83a69c7e2260d4f8',
    messagingSenderId: '360056616553',
    projectId: 'chat-app-2ac67',
    authDomain: 'chat-app-2ac67.firebaseapp.com',
    storageBucket: 'chat-app-2ac67.firebasestorage.app',
    measurementId: 'G-WQHEFTNYGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLkPCYSmt1YpOq6bC9-c5ZbnMl-WWNEas',
    appId: '1:360056616553:android:32c50d94da08245e60d4f8',
    messagingSenderId: '360056616553',
    projectId: 'chat-app-2ac67',
    storageBucket: 'chat-app-2ac67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM40MNXJpcxMYxVGWSSDsQ16GwHv5Pk4o',
    appId: '1:360056616553:ios:b824aff3a6389a0860d4f8',
    messagingSenderId: '360056616553',
    projectId: 'chat-app-2ac67',
    storageBucket: 'chat-app-2ac67.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM40MNXJpcxMYxVGWSSDsQ16GwHv5Pk4o',
    appId: '1:360056616553:ios:b824aff3a6389a0860d4f8',
    messagingSenderId: '360056616553',
    projectId: 'chat-app-2ac67',
    storageBucket: 'chat-app-2ac67.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDle2wA0Z__I_SShGNLg8fxuiIuh8_I7GM',
    appId: '1:360056616553:web:27988e77c48d22b260d4f8',
    messagingSenderId: '360056616553',
    projectId: 'chat-app-2ac67',
    authDomain: 'chat-app-2ac67.firebaseapp.com',
    storageBucket: 'chat-app-2ac67.firebasestorage.app',
    measurementId: 'G-F1LL4YPZJE',
  );
}
